### PR TITLE
Add support for Symfony Form inherit_data

### PR DESCRIPTION
**Pull request by Bartheyrman22**

### CODE REVIEW

**Comment by gilles-g** [comment]
Hi @Bartheyrman22 

Could you show me what you want to do with inherit_data please?

**Comment by Bartheyrman22** [comment]
Hi Gilles,

I want to reuse my `ResultFilterType` that I use seperately in a filter-form.
In a combined filter-form I want to add the `ResultFilterType` as the base table/filter and add the other filtertypes as joined tables/filters. (`OrderFilterType` and `SampleFilterType`).

Basically I found that we need to drop the `result`-alias when `inherit_data` is set. This because it is not used by the form builder itself also.

See the folllowing code snippet.

```php
public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('order', OrderFilterType::class, [
                'add_shared' => function (FilterBuilderExecuterInterface $qbe) {
                    $closure = function (QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) {
                        $filterBuilder->leftJoin(OrderTable::class, $joinAlias, Join::WITH, $alias . '.orderId = ' . $joinAlias . '.orderId');
                    };

                    $qbe->addOnce($qbe->getAlias().'.order', 'o', $closure);
                }
            ])
            ->add('sample', SampleFilterType::class, [
                'add_shared' => function (FilterBuilderExecuterInterface $qbe) {
                    $closure = function (QueryBuilder $filterBuilder, $alias, $joinAlias, Expr $expr) {
                        $filterBuilder->leftJoin(SampleTable::class, $joinAlias, Join::WITH, $alias . '.sampleId = ' . $joinAlias . '.sampleId');
                    };

                    $qbe->addOnce($qbe->getAlias().'.sample', 's', $closure);
                }
            ])
            ->add('result', ResultFilterType::class, [
                'inherit_data' => true
            ])
        ;
    }
``

**Comment by gilles-g** [comment]
Ok thanks, Do you think you could add a test?

**Comment by Bartheyrman22** [comment]
Added an extra test while other tests are still working.

**Comment by Bartheyrman22** [comment]
Hi @gilles-g,
Any feedback so far? Would be nice to see the support in a main release. :wink:

**Review by gilles-g — APPROVED** [review]

**Comment by gilles-g** [comment]
Hi @Bartheyrman22

sorry for the delay, I will merge and create tags

**Pull request merged**
